### PR TITLE
Access devices

### PR DESCRIPTION
**Pull request by jacobalberty**
This contains the 'PUT' pull request as well as the rest of the implementation of #15 . Right now it only includes support for changing the poe settings but the accessDevice object can easily be modified to allow changing of anything in port_overrides.

### CODE REVIEW

**Comment by jens-maus** [comment]
First of all, thanks for the PR. However, would you please again elaborate what this is all about? I still can't get the idea what this additional "accessDevice" functionality is all about and why it requires PUT. So please explain what is currently the limiting point in the current API and what you feel your accessDevice improves.

**Comment by jacobalberty** [comment]
It's for controlling unifi switch ports at this point. I called the class accessDevice to use as generic a name as possible because the same api can be used to change ap settings and gateway settings. So later on it could be expanded to support those.

My use case (and at the moment the only supported api in the class) is to turn on and off poe for individual ports using the accessDevice.setPoe(port, mode) method. port is the port number as seen in the controller under the # field. Method is one of 'off', 'passv24', or 'auto'  and is checked in the setPoe call to be sure one of those is used.

I do not necessarily consider this ready to merge as is, at the very least documentation for the new calls needs to be written up, and perhaps improve accessDevice.validate(). Controller.updateAccessDevice()  right now also just assumes you are changing port_overrides, so there should probably be some method of marking  individual values within accessDevice._device as dirty so that updateAccessDevice knows what to send.

I'm happy to discuss the best way to make those changes and check them in to my local branch to update this PR with those changes as well.

**Comment by jacobalberty** [comment]
oh and PUT support is just a requirement for the specific rest api updateAccessDevice() uses. That's ubiquitis doing, not mine

**Comment by jens-maus** [comment]
Please note that node-unifi is largely based on the unifi API the UniFi-API-Client (https://github.com/Art-of-WiFi/UniFi-API-client) is providing via a php class. And in the past I always tried to be compatible to that API and just update node-unifi with the changes that php class provides to their php users. And if possible I would like to keep that situation and not start branching away from that to much by starting generating own generic interfaces. And AFAICS your accessDevices() is somewhat starting to branch into this direction. 

So please, first have a look at the UniFi-API-client API and see if the same "accessDevices" functionality is already there in newer versions of this client API and if so, we should IMHO mimic in the same compatible way. That's at least what I would probably do to provide this new functionality to set device parameters.

**Comment by jacobalberty** [comment]
Yes...ish it does contain set_device_settings_base, which is roughly the equivalent of updateAccessDevice. principle difference being updateAccessDevice takes just an accessDevice which contains everything. set_device_settings_base takes a device id and device_settings to modify. I do not see anything to assist with generating device_settings for set_device_settings_base which is where most of this PR lies, the actual api changes were minor compared to that.


https://github.com/Art-of-WiFi/UniFi-API-client/blob/master/src/Client.php#L1776

**Comment by jacobalberty** [comment]
I'm working on an alternative implementation that matches the upstream php one, You'll see this branch change to wrap it for my own implementation and testing functionality but ultimately I'll change the PR to match the upstream one

**Comment by jacobalberty** [comment]
I believe pr #18 is closer to what you want, and gets me much closer for my own uses so closing this.

**Pull request closed without merging**
