### PR TITLE
Added function to initiate a speedtest on gateway

### PR DESCRIPTION
**Pull request by kitzler-walli**

### CODE REVIEW

**Comment by jens-maus** [comment]
With the latest node-unifi version a speedtest should be able to be initiated via the public API. Please check and rework your PR in case this is not working or if you think there is some other way to do that.

**Comment by kitzler-walli** [comment]
On your master branch there is no single hint that you implemented the speedtest action so what should have changed?

**Comment by jens-maus** [comment]
You are right, I mixed that up with the fetchSpeedTestResults stuff (https://github.com/jens-maus/node-unifi/blob/master/unifi.js#L763)

Nervertheless, where did you get the info from that a `cmd: speedtest` is enough to actually start a speed test on the gateway? Can you add any reference please.

**Comment by jens-maus** [comment]
Ok, answering my own questions I could find the following unifi wiki resources also pointing at the `speedtest` option:

https://ubntwiki.com/products/software/unifi-controller/api

**Comment by kitzler-walli** [comment]
Sorry for being late with my response - I simply looked at the network traffic in Chrome when starting a speedtest manually.

**Pull request closed without merging**
